ROLE_CLINICAL_ADMIN = "clinical_admin"
ROLE_FIELD_TECHNICIAN = "field_technician"
ROLE_AUDITOR = "auditor"

ROLES = (ROLE_CLINICAL_ADMIN, ROLE_FIELD_TECHNICIAN, ROLE_AUDITOR)

EQUIPMENT_AVAILABLE = "available"
EQUIPMENT_IN_USE = "in_use"
EQUIPMENT_MAINTENANCE = "maintenance"
EQUIPMENT_OFFLINE = "offline"
EQUIPMENT_STATUSES = (
    EQUIPMENT_AVAILABLE,
    EQUIPMENT_IN_USE,
    EQUIPMENT_MAINTENANCE,
    EQUIPMENT_OFFLINE,
)
ACTIVE_EQUIPMENT_STATUSES = (EQUIPMENT_AVAILABLE, EQUIPMENT_IN_USE)

PRIORITY_LOW = "low"
PRIORITY_MEDIUM = "medium"
PRIORITY_CRITICAL = "critical"
PRIORITIES = (PRIORITY_LOW, PRIORITY_MEDIUM, PRIORITY_CRITICAL)

WO_PENDING = "pending"
WO_IN_PROGRESS = "in_progress"
WO_COMPLETED = "completed"
WO_FAILED = "failed"
WORK_ORDER_STATUSES = (WO_PENDING, WO_IN_PROGRESS, WO_COMPLETED, WO_FAILED)
ACTIVE_WORK_ORDER_STATUSES = (WO_PENDING, WO_IN_PROGRESS)
TERMINAL_WORK_ORDER_STATUSES = (WO_COMPLETED, WO_FAILED)

ALLOWED_REPORT_EXTENSIONS = {".txt", ".pdf", ".png", ".jpg", ".jpeg", ".gif", ".webp"}

DEMO_PASSWORD = "Medflow123!"

MAX_PAGE_SIZE = 100
